name: demo-app
version: 0.1
deps:
  - https://raw.githubusercontent.com/moonlibs/config/master/config-scm-1.rockspec
  - https://raw.githubusercontent.com/moonlibs/package-reload/master/package.reload-scm-1.rockspec
  - https://raw.githubusercontent.com/igorcoding/tarantool-spacer/master/spacer-scm-1.rockspec
  - https://raw.githubusercontent.com/tarantool/http/master/rockspecs/http-scm-1.rockspec
tntdeps: {}
